name: upload-release-tarball

on: release

jobs:
  upload-release-tarball:
    name: Upload complete source code including submodules
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - run: |
        set -x
        TAG="${GITHUB_REF#refs/tags/}"
        RELEASE_TARBALL="/tmp/web-eid-app-${TAG}.tar.gz"
        git archive --verbose --format=tar --output="${RELEASE_TARBALL}" "${TAG}" --
        echo "RELEASE_TARBALL='${RELEASE_TARBALL}'" >> "${GITHUB_ENV}"

    - uses: svenstaro/upload-release-action@v2
      with:
        file: ${{ env.RELEASE_TARBALL }}
